### ISSUE TITLE
跟lombok冲突 

### ISSUE THREAD

**Issue by 157677678** [xuperchain/xasset-sdk-java#16]
实际上 是 xuper-java-sdk 这个包跟 lombok 冲突 我没找到哪里冲突，这个怎么解决呢？

**Comment by FreshmanD** [comment]
这边测试是没问题的哈
```
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
        </dependency>
```

**Comment by 157677678** [comment]
> 

我这边是gradle
`plugins {
id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {

maven {
    url 'https://maven.aliyun.com/repository/public'
}
maven { url "https://jitpack.io" }
mavenCentral()
}

dependencies {
annotationProcessor 'org.projectlombok:lombok'
compileOnly 'org.projectlombok:lombok'
implementation 'com.baidu.xuper:xasset-sdk-java:1.0.4'
implementation 'com.baidu.xuper:xuper-java-sdk:0.2.0'
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
useJUnitPlatform()
}`

build 后结果：
`
Execution failed for task ':compileJava'.

Could not resolve all files for configuration ':compileClasspath'.
Could not find org.projectlombok:lombok:.
Required by:
project :

Possible solution:

Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
`
删除lombok就可以了

**Comment by FreshmanD** [comment]
这个应该不是冲突 是找不到包 这个要看一下http proxy或者环境问题哈

**Comment by 157677678** [comment]
可能其他项目我加springboot 了 谢谢您


> 这个应该不是冲突 是找不到包 这个要看一下http proxy或者环境问题哈
